[workspace]
members = [
    "blockstore",
    "blockstore-ffi",
    "blockstore-cli",
    "blockstore-parser",
]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2024"
authors = ["Ron Kuris <swcafe@gmail.com>"]
license-file = "LICENSE.md"
readme = "README.md"

[workspace.dependencies]
bytemuck = { version = "1.13.1", features = ["derive"] }
xxhash-rust = { version = "0.8.10", features = ["xxh64"] }
tempfile = "3.20.0"
more-asserts = "0.3.1"
criterion = { version = "0.5.1", features = ["html_reports"] }
pprof = { version = "0.15.0", features = ["flamegraph", "criterion"] }
cbindgen = "0.29.0"
strum = { version = "0.27", features = ["derive"] }

[workspace.lints.clippy]
pedantic = "warn"
all = "warn"
cargo = "warn"
absolute-paths = "warn"
arithmetic-side-effects = "warn"
indexing-slicing = "warn"
get-unwrap = "warn"
exit = "warn"
dbg-macro = "warn"
decimal-literal-representation = "warn"

[profile.bench]
debug = true

[patch.crates-io]
leveldb-sys = { git = "https://github.com/rkuris/leveldb-sys.git", branch = "master" }
