[package]
name = "blockstore-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
repository = "https://github.com/rkuris/blockstore"
description = "A tool to import blocks from LevelDB into blockstore"
keywords = ["blockchain", "blockstore", "blockchain-storage"]
categories = ["database-implementations"]

[dependencies]
blockstore = { path = "../blockstore", version = "0.1.0", package = "blockdb" }
clap = { version = "4.5.39", features = ["derive"] }
leveldb = { version = "0.8.6" }
db-key = "0.0.5"
pretty-hex = "0.4.1"
rlp = "0.6.1"

[lints]
workspace = true
