[package]
name = "blockstore"
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
description = "A simple blockchain block store in Rust"
keywords = ["blockchain", "blockstore", "blockchain-storage"]
categories = ["database-implementations"]
repository = "https://github.com/rkuris/blockstore"

[dependencies]
bytemuck.workspace = true
strum.workspace = true
xxhash-rust.workspace = true
snap = { version = "1.1", optional = true }
zstd = { version = "0.13.3", optional = true }
metrics = { version = "0.24.1", optional = true }
coarsetime = { version = "0.1.36", optional = true }

[dev-dependencies]
tempfile.workspace = true
more-asserts.workspace = true
criterion.workspace = true
pprof.workspace = true

[features]
default = [ "zstd" ]
metrics = ["dep:metrics", "dep:coarsetime"]
zstd = ['dep:zstd']
snappy = ['dep:snap']

[[bench]]
name = "bench"
harness = false

[lints]
workspace = true
