[package]
name = "blockstore-ffi"
publish = false
version.workspace = true
edition.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
repository = "https://github.com/rkuris/blockstore"
description = "FFI bindings for the blockstore library"
keywords = ["blockchain", "blockstore", "blockchain-storage"]
categories = ["database-implementations"]

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
blockstore = { path = "../blockstore", version = "0.3.0", package = "blockdb" }

[build-dependencies]
cbindgen.workspace = true 

[lints]
workspace = true
